server:
  port: 6789
  #logging config
logging:
  level:
    org: INFO
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ccq-manage-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_website
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver

export:
  excel: